[IMP] handlers

diff --git a/kvash b/kvash
--- a/kvash
+++ b/kvash
@@ -93,10 +93,9 @@ ${project} dict del key prop
 EOF
 )"
 
-help () {
-    echo "${helpMessage}"
-    exit
-}
+#
+# TOOLS
+#
 
 # check arg
 # checkArg name var
@@ -108,9 +107,18 @@ checkArg () {
 }
 
 #
-# shkv ls [search]
+# HANDLERS
 #
-lsKeys () {
+
+handler_help () {
+    echo "${helpMessage}"
+    exit
+}
+
+#
+# ls [search]
+#
+handler_ls () {
     local search="$1"
 
     [ -n "${search}" ] && ls -1 "${store}/${key}" | (grep "${search}" || echo "") || ls -1 "${store}/${key}"
@@ -119,7 +127,7 @@ lsKeys () {
 #
 # touch key
 #
-touchKey () {
+handler_touch () {
     local key="$1"
 
     checkArg key "${key}"
@@ -131,7 +139,7 @@ touchKey () {
 #
 # has key
 #
-has () {
+handler_has () {
     local key="$1"
 
     checkArg key "${key}"
@@ -142,7 +150,7 @@ has () {
 #
 # set key value
 #
-setVal () {
+handler_set () {
     local key="$1"
     local value="${*:2}"
 
@@ -155,7 +163,7 @@ setVal () {
 #
 # append key value
 #
-append () {
+handler_append () {
     local key="$1"
     local value="${*:2}"
 
@@ -169,7 +177,7 @@ append () {
 # appendr key value
 # (line after value)
 #
-appendr () {
+handler_appendr () {
     local key="$1"
     local value="${*:2}"
 
@@ -183,7 +191,7 @@ appendr () {
 #
 # get key
 #
-get () {
+handler_get () {
     local key="$1"
 
     checkArg key "${key}"
@@ -195,7 +203,7 @@ get () {
 #
 # path key
 #
-path () {
+handler_path () {
     local key="$1"
 
     checkArg key "${key}"
@@ -207,7 +215,7 @@ path () {
 #
 # del key
 #
-del () {
+handler_del () {
     local key="$1"
 
     checkArg key "${key}"
@@ -219,27 +227,27 @@ del () {
 #
 # list key ...args
 #
-list () {
+handler_list () {
     local listCommand="$1"
 
     checkArg command "${listCommand}"
 
-    declare -F "list_${listCommand}" &> /dev/null && "list_${listCommand}" ${@:2} || echo "${errorBanner}"
+    declare -F "handler_list_${listCommand}" &> /dev/null && "handler_list_${listCommand}" ${@:2} || echo "${errorBanner}"
 }
 
 # list add key item
-list_add () {
+handler_list_add () {
     local key="$1"
     local item="$2"
 
     checkArg key "${key}"
     checkArg item "${item}"
 
-    appendr "${key}" "${item}"
+    handler_appendr "${key}" "${item}"
 }
 
 # list del key item
-list_del () {
+handler_list_del () {
     local key="$1"
     local item="$2"
 
@@ -253,7 +261,7 @@ list_del () {
 }
 
 # list for key func
-list_foreach () {
+handler_list_foreach () {
     local key="$1"
     local callback="$2"
 
@@ -265,20 +273,15 @@ list_foreach () {
 
 
 #
-# list key ...args
+# dict key ...args
 #
-dict () {
+handler_dict () {
     local dictCommand="$1"
     local dictCommandFunctionName="$1"
 
     checkArg command "${dictCommand}"
 
-    # command wrappers (when a command name is bash expression...)
-    case "${dictCommand}" in
-        set) dictCommandFunctionName="setProp";;
-    esac
-
-    declare -F "dict_${dictCommandFunctionName}" &> /dev/null && "dict_${dictCommandFunctionName}" ${@:2} || echo "${errorBanner}"
+    declare -F "handler_dict_${dictCommandFunctionName}" &> /dev/null && "handler_dict_${dictCommandFunctionName}" ${@:2} || echo "${errorBanner}"
 }
 
 # set internal dict content without comments
@@ -297,7 +300,7 @@ dict_setRaw () {
 }
 
 # dict set key prop value comment
-dict_setProp () {
+handler_dict_set () {
     local key="$1"
     local prop="$2"
     local value="$3"
@@ -308,12 +311,12 @@ dict_setProp () {
     checkArg value "${value}"
     checkArg comment "${comment}"
 
-    list_add "${key}" "# [${prop}] $comment"
-    list_add "${key}" "${prop}=${value}"
+    handler_list_add "${key}" "# [${prop}] $comment"
+    handler_list_add "${key}" "${prop}=${value}"
 }
 
 # dict get key prop
-dict_get () {
+handler_dict_get () {
     local key="$1"
     local prop="$2"
 
@@ -322,27 +325,27 @@ dict_get () {
 
     # extract then export as variable
     dict_setRaw "${key}" ".${key}"
-    export $(get ".${key}" | (grep "^${prop}=" || echo ""))
-    del ".${key}"
+    export $(handler_get ".${key}" | (grep "^${prop}=" || echo ""))
+    handler_del ".${key}"
 
     # get variable value
     echo "${!prop}"
 }
 
 # dict get key prop
-dict_props () {
+handler_dict_props () {
     local key="$1"
 
     checkArg key "${key}"
 
     dict_setRaw "${key}" ".${key}"
-    get ".${key}" | xargs
-    del ".${key}"
+    handler_get ".${key}" | xargs
+    handler_del ".${key}"
 }
 
 
 # dict del key prop
-dict_del () {
+handler_dict_del () {
     local key="$1"
     local prop="$2"
 
@@ -355,7 +358,7 @@ dict_del () {
     cat "${store}/${key}" | (grep -v "^# \\[${prop}\\]" || cat "${store}/${key}") > "${store}/.${key}"
     # remove value
     cat "${store}/.${key}" | (grep -v "^${prop}=" || cat "${store}/${key}") > "${store}/${key}"
-    del ".${key}"
+    handler_del ".${key}"
 }
 
 
@@ -373,14 +376,7 @@ main () {
 
     [ "${command}" != "help" ] && mkdir -p "${store}"
 
-    # command wrappers (when a command name is bash expression...)
-    case "${command}" in
-        ls) commandFunctionName="lsKeys";;
-        touch)  commandFunctionName="touchKey";;
-        set) commandFunctionName="setVal";;
-    esac
-
-    declare -F ${commandFunctionName} &> /dev/null && ${commandFunctionName} $@ || echo "${errorBanner}"
+    declare -F "handler_${command}" &> /dev/null && "handler_${command}" $@ || echo "${errorBanner}"
 }
 
 command="$1"
