[ADD] check function args

diff --git a/shkv b/shkv
--- a/shkv
+++ b/shkv
@@ -63,12 +63,24 @@ help () {
     exit
 }
 
+# check arg
+# checkArg name var
+checkArg () {
+    if [ -z "$2" ]; then
+      echo "argument missing: $1"
+      exit 1
+   fi
+}
+
 #
 # set key value
 #
 setVal () {
     local key="$1"
     local value="${*:2}"
+
+    checkArg key "${key}"
+    checkArg value "${value}"
 
     echo -n "${value}" > "${store}/${key}"
 }
@@ -79,6 +91,9 @@ setVal () {
 append () {
     local key="$1"
     local value="${*:2}"
+
+    checkArg key "${key}"
+    checkArg value "${value}"
 
     echo  -n "${value}" >> "${store}/${key}"
 }
@@ -91,6 +106,9 @@ appendr () {
     local key="$1"
     local value="${*:2}"
 
+    checkArg key "${key}"
+    checkArg value "${value}"
+
     echo -n "${value}" >> "${store}/${key}"
     echo "" >> "${store}/${key}"
 }
@@ -100,6 +118,8 @@ appendr () {
 #
 get () {
     local key="$1"
+
+    checkArg key "${key}"
 
     cat "${store}/${key}"
 }
@@ -111,6 +131,8 @@ get () {
 path () {
     local key="$1"
 
+    checkArg key "${key}"
+
     echo "${store}/${key}"
 }
 
@@ -120,6 +142,8 @@ path () {
 #
 del () {
     local key="$1"
+
+    checkArg key "${key}"
 
     rm "${store}/${key}"
 }
@@ -131,6 +155,8 @@ del () {
 list () {
     local listCommand="$1"
 
+    checkArg command "${listCommand}"
+
     declare -F "list_${listCommand}" &> /dev/null && "list_${listCommand}" ${@:2} || echo "${errorBanner}"
 }
 
@@ -139,6 +165,9 @@ list_add () {
     local key="$1"
     local item="$2"
 
+    checkArg key "${key}"
+    checkArg item "${item}"
+
     appendr "${key}" "${item}"
 }
 
@@ -146,6 +175,9 @@ list_add () {
 list_del () {
     local key="$1"
     local item="$2"
+
+    checkArg key "${key}"
+    checkArg item "${item}"
 
     # IMPORTANT: match exact word ^*$ to prevent from removing entries that are not exact (like ending by prop)
     # IMPORTANT: target file can not be the source file, a pivot file is used
@@ -158,6 +190,9 @@ list_foreach () {
     local key="$1"
     local callback="$2"
 
+    checkArg key "${key}"
+    checkArg callback "${callback}"
+
     while read item; do "${callback}" "${item}"; done < "${store}/${key}"
 }
 
@@ -168,6 +203,8 @@ list_foreach () {
 dict () {
     local dictCommand="$1"
     local dictCommandFunctionName="$1"
+
+    checkArg command "${dictCommand}"
 
     # command wrappers (when a command name is bash expression...)
     case "${dictCommand}" in
@@ -180,6 +217,8 @@ dict () {
 # set internal dict content without comments
 dict_setRaw () {
    local key="$1"
+   checkArg key "${key}"
+
    local source="${store}/${key}"
    local target="${store}/${key}_"
 
@@ -193,6 +232,11 @@ dict_setProp () {
     local value="$3"
     local comment="${*:4}"
 
+    checkArg key "${key}"
+    checkArg prop "${prop}"
+    checkArg value "${value}"
+    checkArg comment "${comment}"
+
     list_add "${key}" "# [${prop}] $comment"
     list_add "${key}" "${prop}=${value}"
 }
@@ -201,6 +245,9 @@ dict_setProp () {
 dict_get () {
     local key="$1"
     local prop="$2"
+
+    checkArg key "${key}"
+    checkArg prop "${prop}"
 
     # extract then export as variable
     dict_setRaw "${key}"
@@ -213,6 +260,8 @@ dict_get () {
 dict_props () {
     local key="$1"
 
+    checkArg key "${key}"
+
     dict_setRaw "${key}"
     get "${key}_" | xargs
 }
@@ -222,6 +271,9 @@ dict_props () {
 dict_del () {
     local key="$1"
     local prop="$2"
+
+    checkArg key "${key}"
+    checkArg prop "${prop}"
 
     # IMPORTANT: match start word ^ to prevent from removing entries that are not exact (like ending by prop)
     # IMPORTANT: target file can not be the source file, a pivot file is used
